name: Pull Request Checks

on:
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    strategy:
      matrix:
        php: [ '8.2' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
      - name: Install dependencies
        run: composer update -W --no-progress
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: PHPUnit
        run: composer run-script test
